defaults:
  -
    scope:
      path: ""
    values:
      layout: "layout.pug"
      stylesheet: "layout.css"
      menuWeight: 999
plugins:
  - jekyll-redirect-from
  - jekyll-toc
sass:
  sass_dir: _sass
  style: :compressed
highlighter: rouge
lsi: false
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  extensions: [tables]
source: .
