defaults:
  -
    scope:
      path: ""
    values:
      layout: "gh-basic"
      stylesheet: "gh-basic.css"
      menu_order: 999
sass:
  sass_dir: _sass
  style: :compressed
highlighter: rouge
lsi: false
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  extensions: [tables]
source: .
