defaults:
  -
    scope:
      path: ""
    values:
      layout: "layout.pug"
      stylesheet: "layout.css"
      menuWeight: 999
plugins:
  - jekyll-redirect-from
  - jekyll-toc
sass:
  sass_dir: _sass
  style: :compressed
highlighter: rouge
lsi: false
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  extensions: [tables]
source: .
# Render pages in directories, to avoid .html file endings.
# This matches docs.mesosphere.com's layout.
permalink: pretty
# Used within pages to link to things, like images
baseurl: /dcos-commons
